### ISSUE TITLE
Use rosidl_typesupport_protobuf to convert ROS2 .msg files into .proto files

### ISSUE THREAD

**Issue by LastStarDust** [eclipse-ecal/rosidl_typesupport_protobuf#18]
Hello!
I have a question about a possible use case of rosidl_typesupport_protobuf.
I need to automatically convert ROS2 .msg files into .proto files.
Could rosidl_typesupport_protobuf be modified to build such a tool? Or it would be easier to just start from scratch?
Thanks
Giorgio

**Comment by FlorianReimold** [comment]
Yes, absolutely, it already does exactly that. If you build the typesupport from a workspace with your .msg files, you will find all the .proto files in the build directories (filesystem-search may help you to find them). Keep in mind that it doesn't actually convert .msg to .proto, but rather IDL to .proto. The IDL Format used by ROS2 is an intermediate format. ROS2 has a converter from the legacy ROS1 .msg format to IDL and you will not even notice it if you use the rosidl_typesupport_protobuf as-is. But if you try to modify it, you may notice the dependency. All ROS2 type supports use the IDL format as input, as it is way better structured than the legacy .msg files.

Otherwise, these are the files responsible for converting ROS messages to .proto files:

Directory with empy templates (those actually create the .proto files)
https://github.com/eclipse-ecal/rosidl_typesupport_protobuf/tree/master/rosidl_adapter_proto/resource

The `__init__.py` including the type mapping etc.
https://github.com/eclipse-ecal/rosidl_typesupport_protobuf/blob/master/rosidl_adapter_proto/rosidl_adapter_proto/__init__.py

Note in the `__init__.py` there is a function that hashes the variable names from the .msg to compute the protobuf field number. This is done to achieve up- and downwards compatibility of the proto files, even if you later add or remove fields in the ROS message. If you would like to just start at 1 and keep couting up, you can modify the template file here:
https://github.com/eclipse-ecal/rosidl_typesupport_protobuf/blob/db923a23c6cba436b769c3dbba5a9e448a9b9168/rosidl_adapter_proto/resource/msg.proto.em#L101

**Comment by LastStarDust** [comment]
@FlorianReimold Thank you so much for the quick and detailed reply.
I am happy to know that that feature is included out of the box. So I do not see the need to modify anything.

Since you released it with the Apache v2 license, we would like to include the `rosidl_typesupport_protobuf` source code in a project of ours. We are an aerospace startup company based in Japan.

Do you have any preference about the acknowledgments message?

**Comment by LastStarDust** [comment]
@FlorianReimold 
Forgive me for the dump question, but when you say
> from a workspace with your .msg files

where exactly should I put the .msg files for `rosidl_typesupport_protobuf` to detect them?

**Comment by FlorianReimold** [comment]
Hi @LastStarDust,

Sounds good! We don't have any perference regarding the acknowledge, Just keep all license headers, tell where you got the code from and that it was made by Continental. A link would be nice.

And - of course - it would be awesome if you would contribute improvements and bugfixes to upstream (i.e. to this repository), so everybody can benefit. But as I see you are already doing that anyways.
Btw, is you project open source as well?

**Comment by LastStarDust** [comment]
@FlorianReimold 
In our acknowledgments section, I added a link to this repository and to the Continental homepage.

Our project is closed source, so the source code is only accessible within the company. BTW this is our company: https://www.axelspace.com/

**Comment by LastStarDust** [comment]
@FlorianReimold 
I was able to use this project to convert .msg files into .proto files.
Thank you so much for your support. You saved me a lot of time.

One last question, the field numbers seem to be assigned randomly (probably they are the result of some hashing function).
Would it be possible to have incrementing field numbers?

**Comment by FlorianReimold** [comment]
Yes, that is possible, but currently not the case, as written above. Currently, the field name is hashed to compute the field number. By doing that, you can later add more fields in the .msg file and also re-sort them. As long as the already existing fields keep their name, the resulting .proto files and their serialization are compatible on binary level.

For just starting at 1 and counting up, you need to modify the `msg.proto.em` file. Keep in mind that you then cannot modify the .msg file and still expect nodes and the data from recordings to be compatible anymore.

> Note in the `__init__.py` there is a function that hashes the variable names from the .msg to compute the protobuf field number. This is done to achieve up- and downwards compatibility of the proto files, even if you later add or remove fields in the ROS message. If you would like to just start at 1 and keep couting up, you can modify the template file here:
> 
> https://github.com/eclipse-ecal/rosidl_typesupport_protobuf/blob/db923a23c6cba436b769c3dbba5a9e448a9b9168/rosidl_adapter_proto/resource/msg.proto.em#L101

**Comment by LastStarDust** [comment]
@FlorianReimold Sorry I just noticed that you had already explained that. Thank you again for the reminder and the additional clarifications.
